# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: Python Build


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install setuptools wheel 
        pip install -r requirements.txt

    - name: Test
      run: |
        python unitTest\test.py 
        python unitTest\testWebViewOnEvent.py 

    # 一个版本号只能发布一次到PYPI
    #- name: Build package
    #  run:  |
    #    pip install twine
    #    python setup.py sdist bdist_wheel
    #    twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI_TOKEN }}  dist/*
    #- name: Dump GitHub context
    #  env:
    #    GITHUB_CONTEXT: ${{ toJson(github) }}
    #  run:  echo "$GITHUB_CONTEXT"
