# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: Python Build

on:
  push:
    tags:
      - 'v*' # 当推送以 v 开头的标签时触发
  
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        set PYTHONIOENCODING=utf-8
        python -m pip install --upgrade pip 
        pip install setuptools wheel 
        pip install -r requirements.txt

    #一个版本号只能发布一次到PYPI
    - name: Build package
      run:  |
        pip install twine
        #pypi对文件大小写敏感,要文件名包含工程名
        #python setup.py  sdist 
        python setup.py  bdist_wheel
        twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI_TOKEN }}  dist/*.whl
